### ISSUE TITLE
Incompatibility between Pier One and Docker 1.13

### ISSUE THREAD

**Issue by thanasisk** [zalando-stups/pierone#130]
Hi all,

with Docker client/server 1.13.0 (Ubuntu 16.04 running inside Virtualbox)

[SNIP]

> Sending build context to Docker daemon 90.11 kB
> Step 1/7 : FROM registry.opensource.zalan.do/stups/openjdk:8-54
> target is unknown

[SNIP]

Downgrading to 1.12 solved immediately the problem. Can someone investigate this?

**Comment by dryewo** [comment]
Does it display any error when you `docker pull registry.opensource.zalan.do/stups/openjdk:8-54`?

**Comment by thanasisk** [comment]
> Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

>Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker pull registry.opensource.zalan.do/stups/openjdk:8-54
Error response from daemon: target is unknown

**Comment by hjacobs** [comment]
Confirmed bug with Docker 1.13.0-rc7.

The error is generated by this code line: https://github.com/docker/docker/blob/v1.13.0-rc7/distribution/pull_v2.go#L369

**Comment by hjacobs** [comment]
I used rc3 or rc4 before and it was working with that --- so they broke it in some RC :disappointed: 
Users now see the problem as 1.13 was released 22 hours ago.
I always assumed that if rc3/rc4 works that 1.13 final will work too, but Docker likes to break stuff...

**Comment by hjacobs** [comment]
Upstream issue: https://github.com/docker/docker/issues/30083

**Comment by hjacobs** [comment]
No longer an issue (fixed in Docker) :smile:
