### ISSUE TITLE
no basic auth credentials

### ISSUE THREAD

**Issue by dmigo** [zalando-stups/pierone#150]
Today I had an auth issue. While trying to do `docker push` I was getting the following log:

    ➜ pierone login             
    Getting OAuth2 token "pierone".. OK
    Storing Docker client configuration in /Users/whoever/.docker/config.json.. OK
    ➜ docker push myrepo/...
    The push refers to a repository [myrepo/...]
    a5f591aacc10: Preparing 
    ...
    cb11ba605400: Waiting 
    no basic auth credentials

Recreating `~/config.json` saved me.  
There was `"credsStore": "osxkeychain"` setting In the previous version of the `~/config.json` which was causing me troubles.

BTW 
mac os 10.12.3
pierone cli 1.1.27
docker 17.06.0-ce, build 02c1d87

**Comment by hjacobs** [comment]
Not sure what the problem is, it seems to only happen for Mac users --- here the relevant CLI repo: https://github.com/zalando-stups/pierone-cli

**Comment by dmigo** [comment]
oops! sorry for that!

**Comment by dmigo** [comment]
Recreated [here](https://github.com/zalando-stups/pierone-cli/issues/58)
