### ISSUE TITLE
scm-source metadata should be validated

### ISSUE THREAD

**Issue by aermakov-zalando** [zalando-stups/pierone#151]
Pierone doesn't validate the contents of the scm-source metadata. This means that it's possible to upload an image with the `revision` field set to a short commit ID (`"f549ca3"` instead of a full 40-characters one), or a completely bogus value, and some teams unfortunately have started to rely on this. Working with short commit IDs in other tooling is rather annoying, and it's actually quite possible that this ID will stop being unique in the future.

**Comment by hjacobs** [comment]
I'm not sure whether Pier One should really validate the contents of `scm-source` as it also cannot check whether the git repo is valid (i.e. contained in whitelist), this can still be validated e.g. by Kubernetes Image Policy Webhook.
