### ISSUE TITLE
Allow developing Pierone without authentication layer

### ISSUE THREAD

**Issue by schlomo** [zalando-stups/pierone#18]
When I start Pierone as described in https://github.com/zalando-stups/pierone and search then I get an error with an auth error:
![image](https://cloud.githubusercontent.com/assets/101384/8006786/299515de-0b97-11e5-8ad2-973f88896de3.png)

**Comment by hjacobs** [comment]
sorry, the Docker hub image is outdated (the README is referencing the latest tag, but we haven't updated it in a while) --- I will push a new "latest" version

**Comment by hjacobs** [comment]
@schlomo I updated the README on how to run it locally (you need a PostgreSQL database, e.g. an empty "pierone" DB on localhost:

```
$ docker run -it -p 8080:8080 --net=host stups/pierone
```

**Comment by hjacobs** [comment]
running without the HTTP_TOKENINFO_URL environment variable will disable OAuth2

**Comment by hjacobs** [comment]
As explained, running Pier One is possible by leaving out the HTTP_TOKENINFO_URL environment variable.
