### ISSUE TITLE
Implement Docker Registry API v2

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/pierone#2]
See the proposal regarding JSON Registry API v2.1: https://github.com/docker/docker/issues/9015

Currently Pier One simply returns 404 for "GET /v2/" to tell the Docker client that only API v1 is implemented.

**Comment by mnuessler** [comment]
Is there already a plan/time frame when support for the v2 API will be implemented?

**Comment by hjacobs** [comment]
No plans yet, I think the registry API v2 does not offer many benefits for us - we should implement it anyway to not fall behind the Docker roadmap.

Example: Resumable push (https://docs.docker.com/registry/spec/api/) would not be supported by the S3 storage backend directly (Amazon S3 never stores partial objects).

**Comment by hjacobs** [comment]
```
xyz: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
```

**Comment by Terry-Weymouth** [comment]
Ditto

**Comment by hjacobs** [comment]
The feature/docker-registry-api-v2 branch currently has a very early implementation to support API v2, some points to note:
- FS layer blobs are mapped to the existing zp_data.images table.
  - I'm using the blob's digest ("sha256:xxx") as i_image_id.
  - The i_parent_id stays NULL (the new blobs have no longer any relation to other blobs)
- The image manifest is mapped to the existing zp_data.tags table.
  - A new t_manifest column was added to store the v2 manifest JSON
  - A new t_fs_layers column was added to reference all FS layer blob IDs ("digests")

The /v1/ endpoints were not changed. The scm-source endpoint looks in both v1 and v2 image layers.

For the migration:
- Docker client will first try to pull from /v2/ and will fallback to /v1/
- Images need to be pushed again by users before the Docker client loses support for pulling from /v1/

**Comment by hjacobs** [comment]
Sadly the Docker ecosystem is totally confusing all the names, there is no clear definition for:
- FS layer
- blob
- image
- "name"
- tag

According to Docker source code it's now more or less:
- FS layer ~~ blob
- image ~~ manifest + layers
- "name" ~~ repository / artifact (e.g. "stups/pierone")
- tag ~~ version tag (e.g. "1.0")

**Comment by hjacobs** [comment]
Some limitations of the current implementation:
- it assumes the complete FS layer blob is uploaded via the "PATCH" method (that's how Docker client 1.8.3 does it)
- it only works with SHA-256 digests (that's what Docker client 1.8.3 uses)

**Comment by hjacobs** [comment]
Why do we upgrade to v2 of the Docker Registry API?
- v1 is now deprecated (Docker client already warns when pulling from “legacy” registry)
- v2 has some benefits for us: most notably the Docker image layers are now using content-addressable IDs (SHA-256 digests), this improves de-duplication and therefore speed :-)
