### ISSUE TITLE
Accept services realm credentials

### ISSUE THREAD

**Issue by lmineiro** [zalando-stups/pierone#22]
Credentials made available from mint&berry for each service (application) also belong to a specific team - the one that owns the service/application.

For PierOne purposes those service credentials should also be accepted with the same semantics, particularly push.

As a valid use case, one could use such credentials for a continuous delivery pipeline - pushing new releases to PierOne and instrumenting the remaining STUPS stack (senza & friends) to deploy them.

**Comment by hjacobs** [comment]
Right now this is already possible (but not team based) by granting the "application.write_all" scope to your application, see https://github.com/zalando-stups/pierone/blob/master/src/org/zalando/stups/pierone/api_v1.clj#L50

**Comment by prayerslayer** [comment]
I think this can be closed now https://github.com/zalando-stups/pierone/blob/master/src/org/zalando/stups/pierone/api_v1.clj#L88
