### ISSUE TITLE
README lacking information about scm-source.json file

### ISSUE THREAD

**Issue by mnuessler** [zalando-stups/pierone#26]
According to the instructions in the README, the project should be built with

```
lein do uberjar, docker build`
```

However, this fails due to a missing `scm-source.json` file:

```
Step 10 : COPY target/scm-source.json /
target/scm-source.json: no such file or directory
Docker image could not be built.
```

It would be nice if the instructions would mention that this has to be generated first.

**Comment by hjacobs** [comment]
good point, will fix
