### ISSUE TITLE
Created time of *-SNAPSHOT tags should not change if image reference stays the same

### ISSUE THREAD

**Issue by s-soroosh** [zalando-stups/pierone#30]
Whenever a new image pushed to pierone the "Created" attribute will be updated even if the docker image is as before.

**Comment by hjacobs** [comment]
@psycho-ir you are only talking about SNAPSHOT tags, right?

**Comment by s-soroosh** [comment]
@hjacobs, yes.

**Comment by hjacobs** [comment]
@prayerslayer do you want to tackle this issue?

**Comment by prayerslayer** [comment]
Sure. I’d probably introduce `last_modified` and `last_modified_by` fields for tags if there are no objections. They would only be used for SNAPSHOT tags, of course, as other tags are immutable.
