### ISSUE TITLE
Allow us to reference to latest docker images with version using badges.

### ISSUE THREAD

**Issue by kanuku** [zalando-stups/pierone#52]
Would it not be cool if we could use badges to point to the latest created image version on pierone?
By badges I mean the ones like on [http://shields.io/](http://shields.io/).

**Comment by hjacobs** [comment]
I assume you mean badges for the Open Source registry (https://registry.opensource.zalan.do/ui/), right?

**Comment by kanuku** [comment]
Yes, I mean for the open source registry.

**Comment by hjacobs** [comment]
:+1:

**Comment by prayerslayer** [comment]
Nice idea :+1: Also makes sense for Pierone I think, for internal documentation.

**Comment by kanuku** [comment]
Like this project:
https://github.com/jekyll/docker
