### ISSUE TITLE
SCM Source (incl. git revision) must be unique for an application

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/pierone#56]
The git rev number cannot be reused for the same application

**Comment by hjacobs** [comment]
The uniqueness can be achieved with Docker Registry API v2 as the image IDs are SHA-256 digests (i.e. changing if and only if the content changes).

**Comment by hjacobs** [comment]
To rephrase: Pier One could enforce that the same scm-source.json contents cannot be used for different images (i.e. different image contents).

**Comment by sarnowski** [comment]
I am not sure about the unique factor: Unfortunatly, a lot of commands in Dockerfiles are non-deterministic like `apt-get update && apt-get upgrade`. This means, for the exact same git revision, you can get different Docker images. Especially for only applying an Ubuntu securty update, it wouldn't be necessary to have any git commits but only a Docker rebuild with `no-cache`.

**Comment by hjacobs** [comment]
@sarnowski very true. In the light of this fact I would reconsider this feature request and advice not to enforce anything in Pier One.

**Comment by mrandi** [comment]
+1 absolutely right. will close it ;(
