### ISSUE TITLE
With new API, images with SNAPSHOT suffixes are not updated

### ISSUE THREAD

**Issue by csenol** [zalando-stups/pierone#59]
If I create an image with -SNAPSHOT suffix, I am able to push without any error, but `pierone scm-source team artifact` returns old information.

**Comment by ramirantala** [comment]
I can confirm. When you push with -SNAPSHOT, there are no error messages, but when you pull, you get old images.

**Comment by hjacobs** [comment]
I will check.

**Comment by mkunz** [comment]
If you do pierone tags -o text TEAM_ID | grep APP_ID you can see that the timestamp has not changed after pushing the snapshot

**Comment by hjacobs** [comment]
This was fixed and released in https://github.com/zalando-stups/pierone/releases/tag/1.8.4

**Comment by hjacobs** [comment]
Apparently this is still buggy for images/tags pushed with API v1 and updated with API v2.

**Comment by csenol** [comment]
Working as expected.
