### ISSUE TITLE
Hide artifacts on pierone list

### ISSUE THREAD

**Issue by okarahan** [zalando-stups/pierone#64]
Is it possible to provide a feature, where you can hide artifacts when executing "pierone artifacts teamname". Sometimes you create artifacts and don't use them in future and they are shown in the pierone list and the overview gets lost.

**Comment by hjacobs** [comment]
Please file this issue in https://github.com/zalando-stups/pierone-cli

**Comment by okarahan** [comment]
Ah ok, sorry.
