### ISSUE TITLE
Cannot update SNAPSHOT images with 1.11 client

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/pierone#77]
Using Docker client version `Docker version 1.11.0, build 4dc5990?`. `docker info` yields

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 34
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 85
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.1.19-boot2docker
Operating System: Boot2Docker 1.11.0 (TCL 7.0); HEAD : 32ee7e9 - Wed Apr 13 20:06:49 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.1 MiB
Name: default
ID: EU25:XRCY:ZLTG:35BU:LNNQ:IC4N:WBFM:YWYM:OO2T:FWD3:I4Z5:XHDO
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 12
 Goroutines: 30
 System Time: 2016-05-04T15:18:42.278027924Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

Steps to reproduce:
- Build Docker image and push with a SNAPSHOT tag
- Build again with `no-cache` option
- Push again, will fail with `invalid checksum digest format`

Probably this is related to the fact that after the first push, the manifest is returned as version 2. After trying to push a second time, it is returned as version 1. (Verify with `GET /v2/:team/:artifact/manifests/:tag`.)

**Comment by georghildebrand** [comment]
@prayerslayer, is there already a fix for this bug?

**Comment by hjacobs** [comment]
@georghildebrand no, there is no fix yet --- I personally would just remove the support for `*-SNAPSHOT` altogether.

**Comment by prayerslayer** [comment]
Maybe we can remove `*-SNAPSHOT` and in exchange bring back `latest` :grin:

**Comment by georghildebrand** [comment]
@hjacobs thanks for clearing that up. I in general liked the idea of -SNAPSHOT for situations where its not possible to eg. debug in the local system. The latest tag would help here just to make the iterative deployment easier...

**Comment by hjacobs** [comment]
@prayerslayer `latest` support is fine as long as Fullstop checks whether it's used for "production" (everything is production!) deployments, i.e. raising a violation for use of `latest`.

**Comment by dryewo** [comment]
@hjacobs another use case for `latest` is base images, it's very tempting to put `openjdk:latest` there and never have to care about it any more.

**Comment by hjacobs** [comment]
We had this (`latest`) already with #21 (I created the issue myself), not sure why it was closed/abandoned.

**Comment by prayerslayer** [comment]
It was there and did work for some time, I added the feature. Dunno what broke it. Regarding fullstop I don't think it's necessary to check as deploying `latest` is bad practice, but not problematic in terms of traceability. (Assuming deployed `latest` has proper `scm-source`, but that's checked anyways or will be.)
