### ISSUE TITLE
Add possibility to mark images as unuseable

### ISSUE THREAD

**Issue by lenalebt** [zalando-stups/pierone#94]
Currently, there is no possibility to delete images in pierone. This is a good thing, since we force immutability. Nevertheless, sometimes there is the need to make sure an image is not used anymore, for example because it is broken or imposes security risks.

I am looking for a feature to mark images as deleted / unuseable. I would expect that one still is able to download the images somehow (because you should always be able to inspect its contents), but it should not work by default. This way, one would make machine creation with e.g. senza impossible.

**Comment by hjacobs** [comment]
This is also related to https://github.com/zalando-stups/pierone-cli/issues/25 (hide some artifacts in Pier One CLI output)

**Comment by hjacobs** [comment]
:+1: for some new flag ("active"? "deleted"?) for image tags, this is also interesting in combination with the new Clair severity information (images with security issues could be "decommissioned").

**Comment by sarnowski** [comment]
It must not be "docker pullable" if its "inactive".

**Comment by dryewo** [comment]
Who should be authorized to do this? Deactivating some important image may result in failed builds or even deployments, having an impact on production.

So far the concept looks like this:

```
$ pierone deactivate stups openjdk 8-30 "No longer supported"
$ pierone activate stups openjdk 8-30 "Oops, wrong image"
```
