### ISSUE TITLE
clair endpoint invalid certificate

### ISSUE THREAD

**Issue by matosf** [zalando-stups/pierone#97]
https://clair.opensource.zalan.do uses a invalid certificate for this domain.

the one used is valid only for:

```
catwatch.opensource.zalan.do
opensource.zalan.do
registry-write.opensource.zalan.do
registry.opensource.zalan.do
```

**Comment by hjacobs** [comment]
@matosf yes, this is known and @sarnowski is on it.

**Comment by dryewo** [comment]
It's fixed now.
